"use client"

import Nav from '@/components/Moodle/Nav'
import Menu from '@/components/Moodle/menu'
import PlugIn from '@/components/Plugin/PlugIn'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Container = styled.div`
  width:1000px;
  display:flex;
`

export default function Home() {
  return (
    <main>
      <Head>
        <title>StudyWithEase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Container>
        <Menu/>
        <PlugIn/>
      </Container>
    </main>
  )
}
