"use client"

import Nav from '@/components/Moodle/Nav'
import Menu from '@/components/Moodle/menu'
import PlugIn from '@/components/Plugin/PlugIn'
import TimeWizard from '@/components/Plugin/TimeWizard/TimeWizard'
import Head from 'next/head'
import { useState } from 'react'
import styled from 'styled-components'

const Container = styled.div`
  width:100vw;
  height:100vh;
  display:flex;
  background-color: #f8f9fa;
  overflow: scroll;
  display: grid;
  grid-template-areas: 
    "header header header"
    "menu plugin wizard"
    ;
  grid-template-columns: auto minmax(600px, 1fr) auto;
  grid-template-rows: 50px auto;
  overflow: scroll;
  align-items: center;
`

const InitialDate = new Date(2023,9,15)

export default function Home() {

  const getDate = () => {
    let date;
    if (typeof window !== 'undefined') {
      // Perform localStorage action
      const storedDate = localStorage.getItem("study-with-ease-date")
      if(storedDate){
        date = new Date(JSON.parse(storedDate))
      } else {
        date = InitialDate;
      }
    } else {
      date = InitialDate;
    }
    return date;
  }

  const setDate = (date: Date) => {
    const string = JSON.stringify(date);
    localStorage.setItem("study-with-ease-date", string)
    setCurrentDate(date)
  }

  const [currentDate, setCurrentDate] = useState<Date>(getDate());
  const [reset, setReset] = useState<boolean>(false);

  return (
    <main>
      <Head>
        <title>StudyWithEase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Nav/>
        <Menu/>
        <PlugIn reset={reset} setReset={setReset} currentDate={currentDate} />
        <TimeWizard reset={reset} setReset={setReset} setDate={setDate} date={currentDate}/>
      </Container>
    </main>
  )
}
